### ISSUE TITLE
Issue with run python demo.py and bindings 

### ISSUE THREAD

**Issue by ChrisDelClea** [mmxgn/minie#1]
Hey @mmxgn,

first of all, thanks for sharing this! 
 I followed the setup you described., then, when I want to run the bindings as well as the demo.py.
Unfortunately when i try to run demo.py I get:
```
Traceback (most recent call last):
  File "demo.py", line 31, in <module>
    parser = CoreNLPUtils.StanfordDepNNParser()
  File "jnius/jnius_export_class.pxi", line 856, in jnius.JavaMethod.__call__
  File "jnius/jnius_export_class.pxi", line 1028, in jnius.JavaMethod.call_staticmethod
  File "jnius/jnius_jvm_dlopen.pxi", line 91, in jnius.create_jnienv
jnius.JavaException: JVM exception occurred: Error creating edu.stanford.nlp.time.TimeExpressionExtractorImpl edu.stanford.nlp.util.ReflectionLoading$ReflectionLoadingException
```

In the case of using the bindings:
```
jar_file = "absolute/path/to/.jar"
minie = MinIE(jar_file)
# Sentence to extract triples from
sentence = "The Joker believes that the hero Batman was not actually born in foggy Gotham City."
triples = [p.triple for p in minie.get_propositions(sentence)]
```

TypeError: __init__() takes 1 positional argument but 2 were given
If i remove the jar_file from the constructor:

```
---> 46         CoreNLPUtils = autoclass('de.uni_mannheim.utils.coreNLP.CoreNLPUtils')
     47 
     48         # Dependency parsing pipeline initialization

~/opt/anaconda3/lib/python3.8/site-packages/jnius/reflect.py in autoclass(clsname, include_protected, include_private)
    227 
    228     # c = Class.forName(clsname)
--> 229     c = find_javaclass(clsname)
    230     if c is None:
    231         raise Exception('Java class {0} not found'.format(c))

jnius/jnius_export_func.pxi in jnius.find_javaclass()

jnius/jnius_jvm_dlopen.pxi in jnius.create_jnienv()

JavaException: JVM exception occurred: de/uni_mannheim/utils/coreNLP/CoreNLPUtils java.lang.NoClassDefFoundError

``` 

Do you know what goes wrong or how to fix it?

**Comment by mmxgn** [comment]
Hi,

I will check it today.

Just a question, did you remember to change:

```
jar_file = "absolute/path/to/.jar"
```

to the minie  `.jar` path?

**Comment by mmxgn** [comment]
Ok fixed it.

The problem was the example I gave was not correct. Instead of `jar_file = "path/to/jar"` it should have been:

```
import os
os.environ['CLASSPATH'] = "path/to/jar"
```

I had changed the class `__init__` without appropriately changing the example. I updated `README.md` to reflect that. Try it and if it works for you you can close the issue.

Thanks for your interest in the python bindings for MinIE

**Comment by heathersherry** [comment]
I also came across the same error when executing with Java 11.
However, everything works well with Java 8.
